name: Build Jellyfin Tizen

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-wgt:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Install Tizen Studio
        run: |
          sudo apt update
          sudo apt install -y pciutils zip libncurses5 python libpython2.7
          sudo apt clean
          curl https://usa.sdk-dl.tizen.org/web-cli_Tizen_Studio_4.5.1_usa_ubuntu-64.bin -o install.bin
          chmod a+x install.bin
          ./install.bin --accept-license $HOME/tizen-studio
          rm install.bin
      - name: Install Tizen packages
        run: |
          $HOME/tizen-studio/package-manager/package-manager-cli.bin install \
          Certificate-Manager NativeCLI cert-add-on --accept-license
      - name: Prepare Jellyfin Web
        run: |
          git clone https://github.com/jellyfin/jellyfin-web.git
          cd jellyfin-web
          git checkout be195b0
          yarn install --frozen-lockfile
      - name: Prepare Jellyfin Tizen
        run: |
          git clone https://github.com/ilteoood/jellyfin-tizen.git
          cd jellyfin-tizen
          JELLYFIN_WEB_DIR=../jellyfin-web/dist yarn install
      - name: Manage sign certificate
        run: |
          export REPLACE_PATH=$(echo $HOME | sed 's/\//\\\//g')
          export PATH=$PATH:$HOME/tizen-studio/tools/ide/bin
          export TV_DUID=$(cat ./jellyfin-tizen/tv-duid.txt | while read line || [[ -n $line ]]; do echo -n "<TestDevice>$line</TestDevice>"; done)
          pip install gdown
          gdown --id ${{ secrets.CERTIFICATE_LOCATION }}
          unzip tizen-certificates.zip
          sed -i "s/\/home\/ilteoood/$REPLACE_PATH/g" ./profile/profiles.xml
          mv ./profile $HOME/tizen-studio-data
          pwd
          ls -la
          ls -la ./SamsungCertificate
          sed -i "s/<TestDevice>AABCD<\/TestDevice>/$TV_DUID/g" $HOME/SamsungCertificate/jellyfin/device-profile.xml
      - name: Run Tizen CLI build
        run: |
          cd jellyfin-tizen
          export PATH=$PATH:$HOME/tizen-studio/tools/ide/bin
          tizen security-profiles set-active -n jellyfin
          tizen build-web -e ".*" -e gulpfile.js -e README.md -e "node_modules/*" -e "package*.json" -e "yarn.lock"
          tizen package -t wgt -o . -- .buildResult -s Jellyfin
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jellyfin-10.7.7
          path: ./jellyfin-tizen/Jellyfin.wgt